name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Rust toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Download flatpak cargo generator
        run: | 
          wget https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/refs/heads/master/cargo/flatpak-cargo-generator.py

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary and generate required flatpak manifests
        working-directory: ./target/release
        run: |
          mv xlm xlm-x86_64-unknown-linux-gnu
          python3 flatpak-cargo-generator.py Cargo.lock

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            ./target/release/xlm-x86_64-unknown-linux-gnu

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./target/release/xlm-x86_64-unknown-linux-gnu
            ./generated-sources.json
