name: "Release"

on:
  push:
    tags: 
        - "v*.*.*"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Rust toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          toolchain: stable
          components: rustfmt, clippy
            
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release

      - name: Generate checksum
        working-directory: ./target/release
        run: sha256sum xlm > xlm.sha256sum

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./target/release/xlm
            ./target/release/xlm.sha256sum