name: "Release"

on:
  push:
    tags: 
        - "v*.*.*"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Rust toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          components: rustfmt, clippy
            
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary and generate checksum
        working-directory: ./target/release
        run: |
          mv xlm xlm-x86_64-unknown-linux-gnu
          sha256sum xlm-x86_64-unknown-linux-gnu > xlm-x86_64-unknown-linux-gnu.sha256sum

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            ./target/release/xlm-x86_64-unknown-linux-gnu
            ./target/release/xlm-x86_64-unknown-linux-gnu.sha256sum

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./target/release/xlm-x86_64-unknown-linux-gnu
            ./target/release/xlm-x86_64-unknown-linux-gnu.sha256sum